---
- name: Installing Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  sudo: yes
  with_items:
    - python-lxml
    - python-shapely
    - python-dateutil
    - python-xlrd
    - python-xlwt
    - python-dev
    - python-pip

- name: Clone Web2py
  git: repo=git://github.com/web2py/web2py.git dest=/home/admin/web2py

- name: Copy routes.py
  copy: src=routes.py dest=/home/admin/web2py/routes.py

- name: Clone Coapp
  git: repo=git://github.com/gnarula/eden_deployment dest=/home/admin/web2py/applications/eden

- name: Move 000_config.py
  command: cp /home/admin/web2py/applications/eden/private/templates/000_config.py /home/admin/web2py/applications/eden/models

- name: Editing 000_config.py
  lineinfile: dest=/home/admin/web2py/applications/eden/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^settings.base.template = "default"', line: 'settings.base.template = "setup"' }
    - { regexp: '^FINISHED_EDITING_CONFIG_FILE = False', line: 'FINISHED_EDITING_CONFIG_FILE = True' }
    - { regexp: '^#settings.base.public_url = \"http://127.0.0.1:8000\"', line: 'settings.base.public_url = \"http://{{ sitename }}\"' }


- name: Copy web2py init script
  sudo: yes
  copy: src=web2py dest=/etc/init.d/web2py

- name: update-rc.d
  sudo: yes
  command: update-rc.d web2py defaults

- name: Fix permissions for init.d script
  sudo: yes
  file: path=/etc/init.d/web2py state=file mode=755

- name: Launch Coapp
  sudo: yes
  service: name=web2py state=started
