---
- name: Install MySQL
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb
    - phpmyadmin
    - mytop

- name: Editing my.cnf
  lineinfile: dest=/etc/mysql/my.cnf
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^query_cache_size        = 16M', line: 'query_cache_size = 1M' }
    - { regexp: '^key_buffer              = 16M', line: 'key_buffer = 1M' }
    - { regexp: 'max_allowed_packet      = 16M', line: 'max_allowed_packet = 1M' }

- name: Restarting MySQL
  service: name=mysql state=restarted

- name: Copy backup script
  copy: src=backup dest=/usr/local/bin/backup mode=755

- name: Copy clean script
  copy: src=clean dest=/usr/local/bin/clean mode=755

- name: Copy my.cnf for root user
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=600

- name: Create Database
  mysql_db: name=sahana state=present

- name: Create sahana db user
  mysql_user: "name=sahana password={{ password }} priv=*.*:ALL host=localhost state=present"

- name: Copying 000_config.py
  command: cp /home/web2py/applications/eden/private/templates/000_config.py /home/web2py/applications/eden/models

- name: Configure DB
  lineinfile: dest=/home/web2py/applications/eden/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^#settings.database.db_type = \"mysql\"', line: 'settings.database.db_type = \"mysql\"' }
    - { regexp: '^#settings.database.password = \"password\"', line: 'settings.database.password = \"{{ password }}\"' }
    - { regexp: '^settings.base.migrate = False', line: 'settings.base.migrate = True' }
