- hosts: # db ip
  roles:
  - postgresql
  sudo: true
  vars:
    distro: # wheezy/precise
    dtype: # na/afterprod/beforeprod
    password: # db password
    type: # prod/test/demo

- hosts: # eden ip
  roles:
  - common
  - uwsgi
  - configure
  sudo: true
  vars:
    dtype: # na/afterprod/beforeprod
    db_ip: # the one mentioned above
    db_type: # postgresql/mysql
    hostname: # hostname
    password: # db password
    prepop_options: # template:mandatory
    sitename: # siteurl
    template: # template name
    type: # prod/test/demo
    web_server: # cherokee - TODO: Apache

- hosts: # webserver ip
  roles:
  - cherokee
  sudo: true
  vars:
      eden_ip: # the one mentioned above
      type: # prod/test/demo


