---
- name: Updating hosts file
  lineinfile: dest=/etc/hosts
              regexp="^localhost.localdomain localhost"
              insertafter="^localhost.localdomain localhost"
              line="{{ sitename }} {{ hostname }} localhost.localdomain localhost"
              state=present

- name: Updating hostname file
  template: src=hostname dest=/etc/hostname

- name: Updating mailname file
  template: src=mailname dest=/etc/mailname

- name: Configure for Internet Mail Delivery
  command: dpkg-reconfigure -f noninteractive exim4-config



- name: Editing 000_config.py
  lineinfile: dest=/home/web2py/applications/eden/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^settings.base.template = \"default\"', line: 'settings.base.template = \"{{ template }}\"' }
    - { regexp: '^FINISHED_EDITING_CONFIG_FILE = False', line: 'FINISHED_EDITING_CONFIG_FILE = True' }
    - { regexp: 'akeytochange', line: 'settings.auth.hmac_key = \"{{ sitename }}{{ password }}\"' }
    - { regexp: '^#settings.base.public_url = \"http://127.0.0.1:8000\"', line: 'settings.base.public_url = \"http://{{ sitename }}\"' }
    - { regexp: '^#settings.base.cdn = True', line: 'settings.base.cdn = True' }


- name: Run web2py
  command: sudo -H -u web2py python web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py chdir=/home/web2py

- name: Configuring for Production
  lineinfile: dest=/home/web2py/applications/eden/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: '^#settings.base.prepopulate = 0', line: 'settings.base.prepopulate = 0' }
    - { regexp: '^settings.base.migrate = True', line: 'settings.base.migrate = False' }

- name: Run web2py
  command: sudo -H -u web2py python web2py.py -S eden -M -R applications/eden/static/scripts/tools/compile.py chdir=/home/web2py

- name: Update crontab
  copy: src=cron dest=/etc/crontab

- name: Start services
  service: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: 'cherokee', state: 'restarted' }
    - { name: 'uwsgi-prod', state: 'started' }
  when: web_server == "cherokee"

- name: Stop Rocket Server
  service: name=web2py  state=stopped
  when: inventory_hostname == '127.0.0.1'

- name: Remove port 80 redirection rule
  shell: iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000
  when: inventory_hostname == '127.0.0.1'

- name: Enable production VirtualHost
  command: a2ensite production
  when: web_server == "apache"

- name: Restart apache
  command: apache2ctl restart
  when: web_server == "apache"
