---
- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - automake
    - libtool
    - gettext
    - rrdtool

- name: Clone Repo
  git: repo=http://github.com/cherokee/webserver.git dest=/home/admin/webserver

- name: Build
  command: "{{ item }} chdir=/home/admin/webserver"
  with_items:
    - ./autogen.sh --prefix=/usr --localstatedir=/var --sysconfdir=/etc
    - make
    - make install

- name: Create log dir
  file: path=/var/log/cherokee state=directory owner=www-data group=www-data

- name: Create graphs dir
  file: path=/var/lib/cherokee/graphs state=directory owner=www-data group=www-data

- name: Copy init.d script
  copy: src=cherokee dest=/etc/init.d/cherokee mode=755

- name: update-rc.d
  command: update-rc.d cherokee defaults

- name: Copying management scripts
  copy: "src={{ item.src }} dest={{ item.dest }} mode=755"
  with_items:
    - { src: 'compile', dest: '/usr/local/bin/compile' }
    - { src: 'pull', dest: '/usr/local/bin/pull' }
    - { src: 'revert', dest: '/usr/local/bin/revert' }
    - { src: 'w2p', dest: '/usr/local/bin/w2p' }

- name: Copying management scripts
  copy: "src={{ item.src }} dest={{ item.dest }} mode=755"
  with_items:
    - { src: 'compile_test.sh', dest: '/usr/local/bin/compile' }
    - { src: 'pull_test.sh', dest: '/usr/local/bin/pull' }
    - { src: 'w2p_test.sh', dest: '/usr/local/bin/w2p' }
  tags:
    - test
    - demo
